name: Publish VS Code Extension

on:
  push:
    branches:
      - main

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v1.6.2
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
